// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/21/2024, 2:30:15 PM
const configMerger = require("/home/farzane/github/new/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/farzane/github/new/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/home/farzane/github/new/layouts/**/*.{vue,js,mjs}","/home/farzane/github/new/pages/**/*.{vue,js,mjs}","/home/farzane/github/new/composables/**/*.{js,ts,mjs}","/home/farzane/github/new/utils/**/*.{js,ts,mjs}","/home/farzane/github/new/{A,a}pp.{vue,js,mjs}","/home/farzane/github/new/{E,e}rror.{vue,js,mjs}","/home/farzane/github/new/app.config.{js,ts,mjs}"] }));

module.exports = config
